feat(aegis1920): JPA와 @Transactinoal에 대한 궁금증 정리
Road-of-CODEr/we-hate-jvm pull request #27
Opened 2021-02-07 09:49 UTC by aegis1920

## 아래의 내용을 채워주세요

1. JPA와 @Transactional
2. JPA에서 @Transactional을 왜 쓸까?
3. 김영한님 강의 및 docs 등등 (파일에 표기해두었습니다!)

기초적인 부분이 많습니다. 아직 초보구나~ 생각하고 보시면 될 것 같습니다ㅎㅎ
틀린 부분이 있다면 피드백주시고 여기 내용에 더 추가하실 부분이 있다면 추가해주셔도 좋습니다. 감사합니다!

2021-02-07 09:59 UTC, J-minkuk commented on JPA/Transactional_Annotation.md
> +> 테스트코드에 @Transactional이 적용됐는지 살펴보고 가능하면 없애자
어떻게 없애요 ??

2021-02-07 10:02 UTC, aegis1920 commented on JPA/Transactional_Annotation.md
> +> 테스트코드에 @Transactional이 적용됐는지 살펴보고 가능하면 없애자
말 그대로 클래스나 메서드에 @Transactional을 적용했다면 @Transactional 부분을 없애자는 의미였습니다!
@DataJpaTest의 경우, 해당 어노테이션을 아예 쓰지 않는 것도 나쁘지 않겠네요. 상황에 따라 다를 것 같습니다 :)

2021-02-07 10:38 UTC, J-minkuk commented on JPA/Transactional_Annotation.md
> +> 테스트코드에 @Transactional이 적용됐는지 살펴보고 가능하면 없애자
DataJpaTest 어노테이션을 사용할 때와 사용하지 않을 때의
테스트 코드 작성 시 어떤 차이가 있는지 먼저 알아보면 좋을 듯 하군요!
테스트 코드 돌려보려고 기존 Service 클래스의 Transactional 어노테이션을 다 주석 처리하기엔 힘들 것 같아요

2021-02-07 14:23 UTC, aegis1920 commented on JPA/Transactional_Annotation.md
> +> 테스트코드에 @Transactional이 적용됐는지 살펴보고 가능하면 없애자
제가 전달을 잘못했나보네요! 없애는 건 기존 Service 클래스의 @Transactional 어노테이션이 아니라 테스트 코드의 @Transactional 입니다!

2021-02-07 15:51 UTC, J-minkuk requested changes

2021-02-07 15:51 UTC, J-minkuk commented on JPA/Transactional_Annotation.md
> +그러면 또 궁금증이 듭니다. `em.find()` 를 했을 때는 트랜잭션을 안 거는 것이 좋을까? 아닙니다. 트랜잭션을 아예 걸지 않으면 모든 SELECT 쿼리마다 commit을 하기 때문에 성능이 떨어집니다. 트랜잭션을 건다면 마지막에 한 번만 commit을 하기 때문에 좀 더 효율적이겠죠? 이외에도 작업을 트랜잭션 단위로 나눈다는 트랜잭션 자체의 장점
트랜잭션을 아예 걸지 않으면 모든 SELECT 쿼리마다 commit을 하게 된다는게 이해가 안돼요 😭 
나는 멍청이야 ㅠㅠ

2021-02-07 15:51 UTC, J-minkuk commented on JPA/Transactional_Annotation.md
> +    }
accessPost 메소드는 조회하는 녀석인 것 같은데 Transactional 어노테이션 없어도 돌아가야 정상아닌가요 ??
(내가 잘못알고 있나..?)

2021-02-07 15:51 UTC, J-minkuk commented on JPA/Transactional_Annotation.md
> +    }
그럼 이 테스트 코드에서 class 상단에 DataJpaTest 어노테이션 빼면 에러가 나나요??
제 생각엔 ```JpaRepository를 상속한 PostRepository에서 save()를 사용하면 @Transactional이  이미 있기때문에 사용가능했던 겁니다!```라서 돌아갈 것 같은데....음

2021-02-07 16:03 UTC, huisam approved these changes
정말 JPA는 너무 어렵습니다.. 공부하면 할 수록 ㅠㅠ
정리 더 해주세요!! 갓호빈님

2021-02-07 16:03 UTC, huisam commented on JPA/Transactional_Annotation.md
> +실제로 dirty checking을 하기 위해서 내부적으로 객체를 2개(스냅샷)를 만들어서 비교하는데 readOnly 옵션을 true로 주면 dirty checking을 할 필요가 없기 때문에 스냅샷을 따로 만들지 않습니다.
진짜 엄청중요합니다... 조회시에 `@Transactional` 박혀 있으면 이게 성능 많이 잡아먹어요 ㅠㅠ 👍 
readOnly 꼭 넣어야되요 특히 커스텀 조회 쿼리 경우에는 꼭!

2021-02-07 16:03 UTC, huisam commented on JPA/Transactional_Annotation.md
> +JPA는 트랜잭션을 기반으로 사용됩니다. 그래서 JPA를 사용하면 `@Transactional`을 잘 사용해야 합니다.
아 근데 저 이거 정말 누군가 꼭 해결해주면 좋겠다는 질문인데요.
`A` service 가 최상단에서 `@Transational` 걸고 
`B` service는 하위에서 `@Transactional` 걸었을 때,
```java
public class A {
    private B b;

    @Transactional
    public void save() {
         b.doSomething()
    }
}

public class B {
    @Transactional
    public void doSomething() {
     // 객체 영속성 상태 등록
    }
}
```
이러한 경우에는 객체 영속성 상태가 A의 Transactional 이 끝날 때까지 반영되는 건가요.?

2021-02-07 16:09 UTC, huisam commented on JPA/Transactional_Annotation.md
> +    }
어 그러게요..? 엥 .?? 요거 의도하신거 설명 부탁드립니다!!

2021-02-07 16:13 UTC, J-minkuk requested changes

2021-02-07 16:13 UTC, J-minkuk commented on JPA/Transactional_Annotation.md
> +실제로 dirty checking을 하기 위해서 내부적으로 객체를 2개(스냅샷)를 만들어서 비교하는데 readOnly 옵션을 true로 주면 dirty checking을 할 필요가 없기 때문에 스냅샷을 따로 만들지 않습니다.
JPA 이게 뭔가 은근 신경써야되는게 많은 것 같네요

2021-02-07 16:15 UTC, aegis1920 commented on JPA/Transactional_Annotation.md
> +    }
단순히 조회만 하면 없어도 돌아가지만 Post안에 List<Comment> 즉, LazyLoading 되어있는 부분을 가져오기 때문에 트랜잭션이 필요합니다! 제가 Post안에 List<Comment>가 있고 OneToMany, 양방향, Lazy로 설정되어있다는 부연 설명을 넣지 않았네요;; 넣도록하겠습니다 하하... 지적 감사합니다!

2021-02-07 16:18 UTC, aegis1920 commented on JPA/Transactional_Annotation.md
> +    }
넵! 트랜잭션이 없는 @SpringBootTest 를 넣고 하면 위에 제가 말씀드리지 못했던 Lazy Loading 하는 부분에서 에러가 납니다!

2021-02-07 16:19 UTC, aegis1920 commented on JPA/Transactional_Annotation.md
> +실제로 dirty checking을 하기 위해서 내부적으로 객체를 2개(스냅샷)를 만들어서 비교하는데 readOnly 옵션을 true로 주면 dirty checking을 할 필요가 없기 때문에 스냅샷을 따로 만들지 않습니다.
조언 감사합니다! 갓휘진님ㅎㅎ 💯

2021-02-07 16:28 UTC, aegis1920 commented on JPA/Transactional_Annotation.md
> +그러면 또 궁금증이 듭니다. `em.find()` 를 했을 때는 트랜잭션을 안 거는 것이 좋을까? 아닙니다. 트랜잭션을 아예 걸지 않으면 모든 SELECT 쿼리마다 commit을 하기 때문에 성능이 떨어집니다. 트랜잭션을 건다면 마지막에 한 번만 commit을 하기 때문에 좀 더 효율적이겠죠? 이외에도 작업을 트랜잭션 단위로 나눈다는 트랜잭션 자체의 장점
저도 이 부분은 찾아보다가 넣은 건데요! 출처에 남겨놓은 [손권남님의 글](https://kwonnam.pe.kr/wiki/springframework/transaction)에 이렇게 나와있더라구요!
저도 정확히는 잘 모르겠지만 트랜잭션을 걸지 않는다면 트랜잭션 단위로 묶지 못해서 하나하나 DB에 반영해야한다는 것으로 이해했습니다 :) 형님 생각도 말씀해주시면 감사하겠습니닷ㅎㅎ

2021-02-07 16:47 UTC, aegis1920 commented on JPA/Transactional_Annotation.md
> +JPA는 트랜잭션을 기반으로 사용됩니다. 그래서 JPA를 사용하면 `@Transactional`을 잘 사용해야 합니다.
넵! 현재 주어진 상태에서는 그렇습니다. 혹시 몰라서 OSIV를 끄고 직접 테스트코드를 돌려봤는데요! 두 곳 모두 `em.contains()` 값이 `true`가 나오는 걸 확인했습니다 :)

2021-02-07 16:51 UTC, J-minkuk commented on JPA/Transactional_Annotation.md
> +JPA는 트랜잭션을 기반으로 사용됩니다. 그래서 JPA를 사용하면 `@Transactional`을 잘 사용해야 합니다.
결국 가장 바깥의 Transactional이 주인이 되는 것?

2021-02-07 16:53 UTC, J-minkuk commented on JPA/Transactional_Annotation.md
> +    }
헐 LazyLoading 하려면 Transactional이 필요하구나 😨

2021-02-07 16:54 UTC, aegis1920 commented on JPA/Transactional_Annotation.md
> +JPA는 트랜잭션을 기반으로 사용됩니다. 그래서 JPA를 사용하면 `@Transactional`을 잘 사용해야 합니다.
흠... 주인이라기보다 연결된 트랜잭션까지 영속성 상태가 유지된다고 보면 될 것 같아요!

2021-02-07 16:59 UTC, J-minkuk commented on JPA/Transactional_Annotation.md
> +    }
@aegis1920 왜 필요해요..?ㅋㅋㅋㅋㅋㅋ 와 JPA 뭐 이래ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ
그냥 지연 로딩하려면 트랜잭션이 필요한걸 받아들이는게 편한가

암튼 그럼 지금까지 우리가 달았던 comment를 정리하자면
걍 Transactional, Transactional(readOnly=true) 잘 붙이고
테스트 코드에서는 SpringBootTest만 쓰면 크게 이슈 없겠네요??

2021-02-07 17:08 UTC, aegis1920 commented on JPA/Transactional_Annotation.md
> +    }
트랜잭션이 없으면 해당 엔티티는 준영속 상태가 돼서 영속성 관리가 되지 않는 객체로 됩니다! 프록시 객체를 초기화 해줄 수 없는 LazyInitializationException이 뜰거예요!

넵 맞습니닷! 요약을 잘 해주셨네여ㅎㅎ

2021-02-07 17:30 UTC, J-minkuk commented on JPA/Transactional_Annotation.md
> +    }
JPA 정리 부탁드립니다 호빈님 :) ❤️  잘부탁해요.

2021-02-08 07:42 UTC, J-minkuk approved these changes

2021-02-08 09:11 UTC, jjeda commented on JPA/Transactional_Annotation.md
> +그러면 또 궁금증이 듭니다. `em.find()` 를 했을 때는 트랜잭션을 안 거는 것이 좋을까? 아닙니다. 트랜잭션을 아예 걸지 않으면 모든 SELECT 쿼리마다 commit을 하기 때문에 성능이 떨어집니다. 트랜잭션을 건다면 마지막에 한 번만 commit을 하기 때문에 좀 더 효율적이겠죠? 이외에도 작업을 트랜잭션 단위로 나눈다는 트랜잭션 자체의 장점
이거 제 생각인데 

read 작업이더라도 다른 transaction의 연산에의해서 read 하려는 투플이 영향을 받을 수 있기 때문에
read 하는동안 다른 트랜잭션이 변경하지 못하도록 공용 lock을 걸어야 한다고 알고있습니다.

그러니 SELECT 할 모든 쿼리를 묶지않고 하나하나씩 연산이된다면 그때마다 lock 이 걸리니까 성능이 떨어진다는 의미아닐까요

2021-02-08 09:13 UTC, jjeda commented on JPA/Transactional_Annotation.md
> +JPA는 트랜잭션을 기반으로 사용됩니다. 그래서 JPA를 사용하면 `@Transactional`을 잘 사용해야 합니다.
propagation 옵션으로 커스터마이징 할 수 있는걸로 기억하는데 너무 오래돼서 기억이 안나네요..
JPA 공부하고싶다ㅠㅠ

2021-02-08 09:24 UTC, J-minkuk commented on JPA/Transactional_Annotation.md
> +그러면 또 궁금증이 듭니다. `em.find()` 를 했을 때는 트랜잭션을 안 거는 것이 좋을까? 아닙니다. 트랜잭션을 아예 걸지 않으면 모든 SELECT 쿼리마다 commit을 하기 때문에 성능이 떨어집니다. 트랜잭션을 건다면 마지막에 한 번만 commit을 하기 때문에 좀 더 효율적이겠죠? 이외에도 작업을 트랜잭션 단위로 나눈다는 트랜잭션 자체의 장점
transactional isolation level을 같이 생각해야 하는 내용 같군요?!

2021-02-08 10:17 UTC, aegis1920 commented on JPA/Transactional_Annotation.md
> +그러면 또 궁금증이 듭니다. `em.find()` 를 했을 때는 트랜잭션을 안 거는 것이 좋을까? 아닙니다. 트랜잭션을 아예 걸지 않으면 모든 SELECT 쿼리마다 commit을 하기 때문에 성능이 떨어집니다. 트랜잭션을 건다면 마지막에 한 번만 commit을 하기 때문에 좀 더 효율적이겠죠? 이외에도 작업을 트랜잭션 단위로 나눈다는 트랜잭션 자체의 장점
@jjeda lock은 선택사항 아닌가요??

2021-02-08 13:24 UTC, kmdngyu commented on JPA/Transactional_Annotation.md
> +그러면 또 궁금증이 듭니다. `em.find()` 를 했을 때는 트랜잭션을 안 거는 것이 좋을까? 아닙니다. 트랜잭션을 아예 걸지 않으면 모든 SELECT 쿼리마다 commit을 하기 때문에 성능이 떨어집니다. 트랜잭션을 건다면 마지막에 한 번만 commit을 하기 때문에 좀 더 효율적이겠죠? 이외에도 작업을 트랜잭션 단위로 나눈다는 트랜잭션 자체의 장점
transaction을 걸지 않으면 실행 시점에만 persistent 상태가 되어서

2021-02-08 13:35 UTC, aegis1920 commented on JPA/Transactional_Annotation.md
> +그러면 또 궁금증이 듭니다. `em.find()` 를 했을 때는 트랜잭션을 안 거는 것이 좋을까? 아닙니다. 트랜잭션을 아예 걸지 않으면 모든 SELECT 쿼리마다 commit을 하기 때문에 성능이 떨어집니다. 트랜잭션을 건다면 마지막에 한 번만 commit을 하기 때문에 좀 더 효율적이겠죠? 이외에도 작업을 트랜잭션 단위로 나눈다는 트랜잭션 자체의 장점
아하! 그러면 Transaction 없이 em.find()만 계속 날렸을 때 날린만큼 commit이 발생하나요?

2021-02-08 14:45 UTC, jjeda commented on JPA/Transactional_Annotation.md
> +그러면 또 궁금증이 듭니다. `em.find()` 를 했을 때는 트랜잭션을 안 거는 것이 좋을까? 아닙니다. 트랜잭션을 아예 걸지 않으면 모든 SELECT 쿼리마다 commit을 하기 때문에 성능이 떨어집니다. 트랜잭션을 건다면 마지막에 한 번만 commit을 하기 때문에 좀 더 효율적이겠죠? 이외에도 작업을 트랜잭션 단위로 나눈다는 트랜잭션 자체의 장점
오 이거군요

2021-02-11 07:39 UTC, juheekimm commented
와 글을 너무 읽기 좋게 잘 써주셔서 재밌게 읽었습니다!
진짜 이해하기 쉽게 잘 써주신 것 같아요. 이렇게 잘 요약하는 방법을 배우고 싶네요 ㅎㅎ
댓글을 달기엔 제가 아직 많이 부족해서 ㅜㅜ 얼른 열심히 공부해서 댓글을 달아볼게요
이렇게 잘하시는 줄도 모르고.. 저번에 JPA 말한게 너무 부끄럽네요 😭 
고생하셨습니다! 👍 👍

2021-02-27 04:59 UTC, merged